[build]
  command = "chmod +x build-netlify.sh && ./build-netlify.sh"
  # ❌ ELIMINAR: publish = "out"
  # ✅ NUEVO: Dejar que @netlify/plugin-nextjs maneje el publish automáticamente

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin de Next.js (REQUERIDO para API routes)
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Headers específicos para API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store, max-age=0"

# Headers para archivos estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects básicos
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/legacy"
  status = 302

# Catch-all para SPA routing (SOLO para páginas, no API)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { role = ["unauthenticated", "authenticated"] }
  # No aplicar a API routes
  force = false