# Netlify Configuration for Next.js App

[dev]
  command = "node scripts/netlify-dev-wrapper.js"
  port = 8888
  targetPort = 3000
  publish = ".next"
  autoLaunch = false
  framework = "#custom"
  
[dev.environment]
  NETLIFY_DEV_DEBUG = "false"
  DEBUG = ""

[build]
  command = "npm install --production=false && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.12.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variable placeholders (set in Netlify UI)
# OPENAI_API_KEY
# DATABASE_URL
# AUTH0_SECRET
# AUTH0_BASE_URL
# AUTH0_ISSUER_BASE_URL
# AUTH0_CLIENT_ID
# AUTH0_CLIENT_SECRET
# EDGE_STORE_ACCESS_KEY
# EDGE_STORE_SECRET_KEY