[build]
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.5"
  NPM_VERSION = "9.8.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers para CORS en Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# ✅ API ROUTES para Next.js (genérico)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-:splat"
  status = 200

# Auth routes específicos
[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/api-auth-login"
  status = 200

[[redirects]]
  from = "/auth/logout" 
  to = "/.netlify/functions/api-auth-logout"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/api-auth-callback"
  status = 200

# ✅ SPA fallback debe ser el último
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200