[build]
  command = "echo '🔍 Starting build...' && npm install --production=false && echo '📦 Installing function deps...' && cd netlify/functions && npm install && cd ../.. && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.20.5"
  NPM_VERSION = "9.8.1"

# Optimized function configuration for transcription
[functions]
  node_bundler = "esbuild"
  
[functions."transcribe-upload"]
  timeout = 180 # Maximum allowed timeout (3 minutes)
  memory = 3008 # Maximum allowed memory (3GB)
  
[functions."transcribe-server-file"]
  timeout = 180 # Maximum allowed timeout (3 minutes)
  memory = 3008 # Maximum allowed memory (3GB)

[functions.environment]
  # Xenova/transformers.js configuration
  TRANSFORMERS_CACHE = "/tmp/.cache"
  HF_HOME = "/tmp/.cache"
  # Disable telemetry for performance
  DO_NOT_TRACK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers para CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# ✅ ESPECÍFICOS PRIMERO - Transcription endpoints
[[redirects]]
  from = "/api/transcribe-server-file"
  to = "/.netlify/functions/transcribe-server-file"
  status = 200

[[redirects]]
  from = "/api/transcribe-upload"
  to = "/.netlify/functions/transcribe-upload"
  status = 200

# Auth routes específicos
[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/api-auth-login"
  status = 200

[[redirects]]
  from = "/auth/logout" 
  to = "/.netlify/functions/api-auth-logout"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/api-auth-callback"
  status = 200

# ✅ GENÉRICO AL FINAL - para otras API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-:splat"
  status = 200

# ✅ SPA fallback - ÚLTIMO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200