/**
 * Auto-generated TypeScript definitions for English translations
 * Generated by Performance Revolution System
 */

export interface ENTranslations {
  // Core translations
  'transcription.title': string;
  'transcription.ready_to_record': string;
  'transcription.start_recording': string;
  'transcription.stop_recording': string;
  'transcription.no_transcript_available': string;
  
  // Language switcher translations
  'language_switcher.current_language': string;
  'language_switcher.medical_certified': string;
  'language_switcher.medical': string;
  'language_switcher.medical_grade': string;
  'language_switcher.validated': string;
  'language_switcher.change_language': string;
  'language_switcher.select_language': string;
  
  // Common translations
  'spanish': string;
  'english': string;
  'spanish_abbr': string;
  'english_abbr': string;
  'clinical_language': string;
  
  // Navigation
  'navigation.dashboard': string;
  
  // Common actions
  'save': string;
  'cancel': string;
  'edit': string;
  'delete': string;
  'create': string;
  'update': string;
  'actions': string;
  
  // Theme
  'light_mode': string;
  'dark_mode': string;
  
  // Demo
  'demo': string;
  'demo_mode_active': string;
  'switch_live_mode': string;
  'demo_login': string;
  'auto_fill_demo': string;
  'demo_mode_full_access': string;
  
  // Auth
  'email': string;
  'password': string;
  'login': string;
  'register': string;
  'login_demo': string;
  
  // Medical
  'consultation.page.title': string;
  'consultation.page.subtitle': string;
  'clinical.notes.title': string;
  'clinical.notes.subtitle': string;
  'orders.categories.medications': string;
  'orders.categories.lab_tests': string;
  'orders.categories.imaging': string;
  'orders.categories.consultations': string;
  
  // Recording
  'recording_started': string;
  
  // Workflow
  'workflow.steps.listen': string;
  'workflow.steps.review': string;
  'workflow.steps.notes': string;
  'workflow.steps.orders': string;
  'workflow.steps.summary': string;
  'workflow.title': string;
  'workflow.subtitle': string;
  'workflow.actions.stop_recording': string;
  'workflow.actions.start_recording': string;
  'workflow.consultation_flow': string;
  'workflow.step_of': string;
  'workflow.medical_navigation': string;
  'workflow.navigation.view_all_patients': string;
  'workflow.navigation.medical_reports': string;
  'workflow.navigation.clinical_history': string;
  'workflow.navigation.new_consultation': string;
  'workflow.current_step': string;
  'workflow.step_descriptions.listen': string;
  'workflow.step_descriptions.review': string;
  'workflow.step_descriptions.notes': string;
  'workflow.step_descriptions.orders': string;
  'workflow.step_descriptions.summary': string;
  
  // Demo specific
  'demo.demo_title': string;
  'demo.patient_selector': string;
  'demo.patient_selector_subtitle': string;
  'demo.request_custom_demo': string;
  
  // Missing key found in code
  '.specialty-confirmation-container': string;
  // Missing key found in code
  'Add Doctor': string;
  // Missing key found in code
  'Add New Patient': string;
  // Missing key found in code
  'Add Study': string;
  // Missing key found in code
  'Error report copied to clipboard for medical team': string;
  // Missing key found in code
  'Función de exportar PDF en desarrollo': string;
  // Missing key found in code
  'Herramientas inteligentes para médicos modernos': string;
  // Missing key found in code
  'Legacy SYMFARMIA System': string;
  // Missing key found in code
  'Loading...': string;
  // Missing key found in code
  'Nota clínica copiada al portapapeles': string;
  // Missing key found in code
  'Please log in to access the legacy system': string;
  // Missing key found in code
  'SYMFARMIA': string;
  // Missing key found in code
  'Test Children Content': string;
  // Missing key found in code
  'Welcome, Dr. Test': string;
  // Missing key found in code
  'activate_advanced_ai': string;
  // Missing key found in code
  'active_patients': string;
  // Missing key found in code
  'active_treatments': string;
  // Missing key found in code
  'ai_assistant': string;
  // Missing key found in code
  'ai_assistant_welcome': string;
  // Missing key found in code
  'ai_insights': string;
  // Missing key found in code
  'ai_medical_insights': string;
  // Missing key found in code
  'ai_powered_clinical_analysis': string;
  // Missing key found in code
  'all_rights_reserved': string;
  // Missing key found in code
  'annual_inefficiency': string;
  // Missing key found in code
  'ask_medical_question': string;
  // Missing key found in code
  'assisted_diagnosis': string;
  // Missing key found in code
  'assisted_diagnosis_desc': string;
  // Missing key found in code
  'automated_prescriptions': string;
  // Missing key found in code
  'automated_prescriptions_desc': string;
  // Missing key found in code
  'avg_treatment_time': string;
  // Missing key found in code
  'basic_mode': string;
  // Missing key found in code
  'benefit_processing': string;
  // Missing key found in code
  'benefit_processing_desc': string;
  // Missing key found in code
  'benefit_report': string;
  // Missing key found in code
  'benefit_report_desc': string;
  // Missing key found in code
  'benefit_speak': string;
  // Missing key found in code
  'benefit_speak_desc': string;
  // Missing key found in code
  'beta_free': string;
  // Missing key found in code
  'burnout_rate': string;
  // Missing key found in code
  'cardiology': string;
  // Missing key found in code
  'change_layout': string;
  // Missing key found in code
  'check_email': string;
  // Missing key found in code
  'check_email_next_steps': string;
  // Missing key found in code
  'choose_transformation_level': string;
  // Missing key found in code
  'clinical.notes.back_to_review': string;
  // Missing key found in code
  'clinical.notes.copied_to_clipboard': string;
  // Missing key found in code
  'clinical.notes.copy': string;
  // Missing key found in code
  'clinical.notes.edit_note': string;
  // Missing key found in code
  'clinical.notes.generate_orders': string;
  // Missing key found in code
  'clinical.notes.generated_by_ai': string;
  // Missing key found in code
  'clinical.notes.save_changes': string;
  // Missing key found in code
  'clinical.notes.soap_note': string;
  // Missing key found in code
  'clinical.quality_indicators.completeness': string;
  // Missing key found in code
  'clinical.quality_indicators.generation_time': string;
  // Missing key found in code
  'clinical.quality_indicators.icd_codes': string;
  // Missing key found in code
  'clinical.quality_indicators.rating': string;
  // Missing key found in code
  'clinical.soap_sections.assessment': string;
  // Missing key found in code
  'clinical.soap_sections.objective': string;
  // Missing key found in code
  'clinical.soap_sections.plan': string;
  // Missing key found in code
  'clinical.soap_sections.subjective': string;
  // Missing key found in code
  'clinical.suggestions.drug_allergies': string;
  // Missing key found in code
  'clinical.suggestions.headache_diary': string;
  // Missing key found in code
  'clinical.suggestions.physical_exam': string;
  // Missing key found in code
  'clinical.suggestions.title': string;
  // Missing key found in code
  'clinical.suggestions.vital_signs': string;
  // Missing key found in code
  'clinical.templates.chief_complaint': string;
  // Missing key found in code
  'clinical.templates.clinical_impression': string;
  // Missing key found in code
  'clinical.templates.cold_compress': string;
  // Missing key found in code
  'clinical.templates.control_appointment': string;
  // Missing key found in code
  'clinical.templates.differential_diagnosis': string;
  // Missing key found in code
  'clinical.templates.followup': string;
  // Missing key found in code
  'clinical.templates.history_present_illness': string;
  // Missing key found in code
  'clinical.templates.hydration': string;
  // Missing key found in code
  'clinical.templates.migraine': string;
  // Missing key found in code
  'clinical.templates.non_pharmacological': string;
  // Missing key found in code
  'clinical.templates.nsaid_trial': string;
  // Missing key found in code
  'clinical.templates.patient_education': string;
  // Missing key found in code
  'clinical.templates.pharmacological_management': string;
  // Missing key found in code
  'clinical.templates.physical_exam': string;
  // Missing key found in code
  'clinical.templates.primary_diagnosis': string;
  // Missing key found in code
  'clinical.templates.rest': string;
  // Missing key found in code
  'clinical.templates.secondary_headache': string;
  // Missing key found in code
  'clinical.templates.systems_review': string;
  // Missing key found in code
  'clinical.templates.tension_headache': string;
  // Missing key found in code
  'clinical.templates.triggers': string;
  // Missing key found in code
  'clinical.templates.triptan_therapy': string;
  // Missing key found in code
  'clinical.templates.urgent_care': string;
  // Missing key found in code
  'clinical.templates.urgent_signs': string;
  // Missing key found in code
  'clinical.templates.virtual_consultation': string;
  // Missing key found in code
  'clinical.templates.vital_signs': string;
  // Missing key found in code
  'clinical_metrics': string;
  // Missing key found in code
  'cofepris_compliance': string;
  // Missing key found in code
  'cofepris_compliance_desc': string;
  // Missing key found in code
  'collective_transformation': string;
  // Missing key found in code
  'common_diagnoses': string;
  // Missing key found in code
  'comprehensive_medical_insights': string;
  // Missing key found in code
  'consultation.actions.export_pdf': string;
  // Missing key found in code
  'consultation.actions.quick_actions': string;
  // Missing key found in code
  'consultation.actions.template_chest_pain': string;
  // Missing key found in code
  'consultation.actions.template_followup': string;
  // Missing key found in code
  'consultation.actions.template_general': string;
  // Missing key found in code
  'consultation.buttons.change_patient': string;
  // Missing key found in code
  'consultation.buttons.save_consultation': string;
  // Missing key found in code
  'consultation.patient_selector.add_new': string;
  // Missing key found in code
  'consultation.patient_selector.subtitle': string;
  // Missing key found in code
  'consultation.patient_selector.title': string;
  // Missing key found in code
  'consultation.status.redirect_notice': string;
  // Missing key found in code
  'consultation.status.saved_success': string;
  // Missing key found in code
  'consultation_settings': string;
  // Missing key found in code
  'consultation_title': string;
  // Missing key found in code
  'contact_sales': string;
  // Missing key found in code
  'contact_soon': string;
  // Missing key found in code
  'conversation.capture.audio_level': string;
  // Missing key found in code
  'conversation.capture.live_transcription': string;
  // Missing key found in code
  'conversation.capture.powered_by_ai': string;
  // Missing key found in code
  'conversation.capture.ready_to_record': string;
  // Missing key found in code
  'conversation.capture.recording_active': string;
  // Missing key found in code
  'conversation.capture.review_dialog_flow': string;
  // Missing key found in code
  'conversation.capture.subtitle': string;
  // Missing key found in code
  'conversation.capture.title': string;
  // Missing key found in code
  'conversation.doctor_speaker': string;
  // Missing key found in code
  'conversation.patient_speaker': string;
  // Missing key found in code
  'conversation.processing.ai_processing': string;
  // Missing key found in code
  'conversation.processing.processing_status': string;
  // Missing key found in code
  'conversation.speakers.ai_medical': string;
  // Missing key found in code
  'cost_per_patient': string;
  // Missing key found in code
  'cta_save_time': string;
  // Missing key found in code
  'cta_sending': string;
  // Missing key found in code
  'custom_pricing': string;
  // Missing key found in code
  'customize_experience': string;
  // Missing key found in code
  'demo_explore_features': string;
  // Missing key found in code
  'demo_interactive': string;
  // Missing key found in code
  'demo_welcome': string;
  // Missing key found in code
  'dermatology': string;
  // Missing key found in code
  'diabetes_trend_up': string;
  // Missing key found in code
  'diagnosis_accuracy': string;
  // Missing key found in code
  'dialogue.sections.associated_symptoms': string;
  // Missing key found in code
  'dialogue.sections.chief_complaint': string;
  // Missing key found in code
  'dialogue.sections.history_present_illness': string;
  // Missing key found in code
  'dialogue.sections.system_review': string;
  // Missing key found in code
  'dialogue.subtitle': string;
  // Missing key found in code
  'dialogue.tags.associated_symptoms': string;
  // Missing key found in code
  'dialogue.tags.duration': string;
  // Missing key found in code
  'dialogue.tags.functional_impact': string;
  // Missing key found in code
  'dialogue.tags.location': string;
  // Missing key found in code
  'dialogue.tags.main_symptom': string;
  // Missing key found in code
  'dialogue.tags.nausea': string;
  // Missing key found in code
  'dialogue.tags.neck_stiffness': string;
  // Missing key found in code
  'dialogue.tags.pain_quality': string;
  // Missing key found in code
  'dialogue.tags.photophobia': string;
  // Missing key found in code
  'dialogue.tags.rps': string;
  // Missing key found in code
  'dialogue.tags.severity': string;
  // Missing key found in code
  'dialogue.tags.vision': string;
  // Missing key found in code
  'dialogue.title': string;
  // Missing key found in code
  'doctors_transformed': string;
  // Missing key found in code
  'dr_ana_location': string;
  // Missing key found in code
  'dr_ana_name': string;
  // Missing key found in code
  'dr_ana_quote': string;
  // Missing key found in code
  'dr_ana_specialty': string;
  // Missing key found in code
  'dr_carlos_location': string;
  // Missing key found in code
  'dr_carlos_name': string;
  // Missing key found in code
  'dr_carlos_quote': string;
  // Missing key found in code
  'dr_carlos_specialty': string;
  // Missing key found in code
  'dr_maria_location': string;
  // Missing key found in code
  'dr_maria_name': string;
  // Missing key found in code
  'dr_maria_quote': string;
  // Missing key found in code
  'dr_maria_specialty': string;
  // Missing key found in code
  'feature_5_consultations': string;
  // Missing key found in code
  'feature_advanced_analytics': string;
  // Missing key found in code
  'feature_ai_diagnosis': string;
  // Missing key found in code
  'feature_automated_prescriptions': string;
  // Missing key found in code
  'feature_basic_reports': string;
  // Missing key found in code
  'feature_basic_transcription': string;
  // Missing key found in code
  'feature_clinic_management': string;
  // Missing key found in code
  'feature_custom_integration': string;
  // Missing key found in code
  'feature_custom_templates': string;
  // Missing key found in code
  'feature_dedicated_support': string;
  // Missing key found in code
  'feature_email_support': string;
  // Missing key found in code
  'feature_multi_doctor': string;
  // Missing key found in code
  'feature_pdf_merger': string;
  // Missing key found in code
  'feature_priority_support': string;
  // Missing key found in code
  'feature_training_included': string;
  // Missing key found in code
  'feature_unlimited_consultations': string;
  // Missing key found in code
  'feature_white_label': string;
  // Missing key found in code
  'final_cta_demo': string;
  // Missing key found in code
  'final_cta_heading': string;
  // Missing key found in code
  'final_cta_signup': string;
  // Missing key found in code
  'final_cta_text': string;
  // Missing key found in code
  'finding_hope_again': string;
  // Missing key found in code
  'follow_up_required': string;
  // Missing key found in code
  'footer_contact': string;
  // Missing key found in code
  'footer_copy': string;
  // Missing key found in code
  'footer_description': string;
  // Missing key found in code
  'footer_privacy': string;
  // Missing key found in code
  'footer_terms': string;
  // Missing key found in code
  'general_medicine': string;
  // Missing key found in code
  'generate_medical_report': string;
  // Missing key found in code
  'hero_cta': string;
  // Missing key found in code
  'hero_heading': string;
  // Missing key found in code
  'hero_subheading': string;
  // Missing key found in code
  'hero_subtitle': string;
  // Missing key found in code
  'hero_title': string;
  // Missing key found in code
  'hope_ecosystem': string;
  // Missing key found in code
  'how_it_works': string;
  // Missing key found in code
  'human_contact_crisis': string;
  // Missing key found in code
  'import_studies': string;
  // Missing key found in code
  'inactive_patients': string;
  // Missing key found in code
  'insurance_claims': string;
  // Missing key found in code
  'intelligent_transcription': string;
  // Missing key found in code
  'intelligent_transcription_desc': string;
  // Missing key found in code
  'join_revolution': string;
  // Missing key found in code
  'join_transformation': string;
  // Missing key found in code
  'journey_progress': string;
  // Missing key found in code
  'medical_analytics': string;
  // Missing key found in code
  'medical_analytics_desc': string;
  // Missing key found in code
  'medical_analytics_overview': string;
  // Missing key found in code
  'medical_crisis': string;
  // Missing key found in code
  'medical_reports': string;
  // Missing key found in code
  'medical_reports_desc': string;
  // Missing key found in code
  'medical_reports_management': string;
  // Missing key found in code
  'medical_time_lost': string;
  // Missing key found in code
  'medication_adherence': string;
  // Missing key found in code
  'mexican_servers': string;
  // Missing key found in code
  'mexican_servers_desc': string;
  // Missing key found in code
  'microphone.actions.diagnose': string;
  // Missing key found in code
  'microphone.actions.retry': string;
  // Missing key found in code
  'microphone.actions.test_access': string;
  // Missing key found in code
  'microphone.status.detected_devices': string;
  // Missing key found in code
  'microphone.status.need_access': string;
  // Missing key found in code
  'microphone.status.problem_with_microphone': string;
  // Missing key found in code
  'microphone.status.problems_detected': string;
  // Missing key found in code
  'microphone.status.recommended_solutions': string;
  // Missing key found in code
  'microphone.status.technical_details': string;
  // Missing key found in code
  'military_encryption': string;
  // Missing key found in code
  'military_encryption_desc': string;
  // Missing key found in code
  'missing.key': string;
  // Missing key found in code
  'money_back_guarantee': string;
  // Missing key found in code
  'new_medical_report': string;
  // Missing key found in code
  'new_patient': string;
  // Missing key found in code
  'new_report': string;
  // Missing key found in code
  'operational_efficiency': string;
  // Missing key found in code
  'orders.consultations.neurology.name': string;
  // Missing key found in code
  'orders.consultations.neurology.reason': string;
  // Missing key found in code
  'orders.consultations.ophthalmology.name': string;
  // Missing key found in code
  'orders.consultations.ophthalmology.reason': string;
  // Missing key found in code
  'orders.details.dose': string;
  // Missing key found in code
  'orders.details.duration': string;
  // Missing key found in code
  'orders.details.indication': string;
  // Missing key found in code
  'orders.entry.back_to_notes': string;
  // Missing key found in code
  'orders.entry.custom_order': string;
  // Missing key found in code
  'orders.entry.custom_order_placeholder': string;
  // Missing key found in code
  'orders.entry.generate_summary': string;
  // Missing key found in code
  'orders.entry.no_orders_selected': string;
  // Missing key found in code
  'orders.entry.selected_orders': string;
  // Missing key found in code
  'orders.entry.subtitle': string;
  // Missing key found in code
  'orders.entry.title': string;
  // Missing key found in code
  'orders.imaging.brain_mri.name': string;
  // Missing key found in code
  'orders.imaging.brain_mri.reason': string;
  // Missing key found in code
  'orders.imaging.head_ct.name': string;
  // Missing key found in code
  'orders.imaging.head_ct.reason': string;
  // Missing key found in code
  'orders.lab_tests.complete_blood_count.name': string;
  // Missing key found in code
  'orders.lab_tests.complete_blood_count.reason': string;
  // Missing key found in code
  'orders.lab_tests.inflammatory_markers.name': string;
  // Missing key found in code
  'orders.lab_tests.inflammatory_markers.reason': string;
  // Missing key found in code
  'orders.medications.ibuprofen.dosage': string;
  // Missing key found in code
  'orders.medications.ibuprofen.duration': string;
  // Missing key found in code
  'orders.medications.ibuprofen.name': string;
  // Missing key found in code
  'orders.medications.paracetamol.dosage': string;
  // Missing key found in code
  'orders.medications.paracetamol.duration': string;
  // Missing key found in code
  'orders.medications.paracetamol.name': string;
  // Missing key found in code
  'orders.medications.sumatriptan.dosage': string;
  // Missing key found in code
  'orders.medications.sumatriptan.duration': string;
  // Missing key found in code
  'orders.medications.sumatriptan.name': string;
  // Missing key found in code
  'other_specialty': string;
  // Missing key found in code
  'page.title': string;
  // Missing key found in code
  'patient_analytics': string;
  // Missing key found in code
  'patient_demographics': string;
  // Missing key found in code
  'patient_list': string;
  // Missing key found in code
  'patient_management': string;
  // Missing key found in code
  'patient_management_preview_description': string;
  // Missing key found in code
  'patient_satisfaction': string;
  // Missing key found in code
  'pdf_export_requested': string;
  // Missing key found in code
  'peace_of_mind_restored': string;
  // Missing key found in code
  'pediatrics': string;
  // Missing key found in code
  'plan_clinic': string;
  // Missing key found in code
  'plan_free': string;
  // Missing key found in code
  'plan_professional': string;
  // Missing key found in code
  'powered_by_ai': string;
  // Missing key found in code
  'preview_footer': string;
  // Missing key found in code
  'quick_insights': string;
  // Missing key found in code
  'readmission_rate': string;
  // Missing key found in code
  'real_doctor_stories': string;
  // Missing key found in code
  'recovery_rate': string;
  // Missing key found in code
  'report_details': string;
  // Missing key found in code
  'reports_analysis': string;
  // Missing key found in code
  'revenue_this_month': string;
  // Missing key found in code
  'review_medication_protocols': string;
  // Missing key found in code
  'revolution_subtitle': string;
  // Missing key found in code
  'sanctuary_subtitle': string;
  // Missing key found in code
  'sanctuary_title': string;
  // Missing key found in code
  'satisfaction_rating': string;
  // Missing key found in code
  'save_settings': string;
  // Missing key found in code
  'schedule_preventive_care': string;
  // Missing key found in code
  'seasonal_trends': string;
  // Missing key found in code
  'select_specialty': string;
  // Missing key found in code
  'session_active': string;
  // Missing key found in code
  'session_inactive': string;
  // Missing key found in code
  'start_free': string;
  // Missing key found in code
  'start_free_trial': string;
  // Missing key found in code
  'start_transformation': string;
  // Missing key found in code
  'step_consult': string;
  // Missing key found in code
  'step_consult_desc': string;
  // Missing key found in code
  'step_processing': string;
  // Missing key found in code
  'step_processing_desc': string;
  // Missing key found in code
  'step_report': string;
  // Missing key found in code
  'step_report_desc': string;
  // Missing key found in code
  'suggested_actions': string;
  // Missing key found in code
  'testimonial_author': string;
  // Missing key found in code
  'testimonial_position': string;
  // Missing key found in code
  'testimonial_quote': string;
  // Missing key found in code
  'testimonial_savings': string;
  // Missing key found in code
  'time_savings': string;
  // Missing key found in code
  'total_patients': string;
  // Missing key found in code
  'total_patients_treated': string;
  // Missing key found in code
  'transcription.ai_active': string;
  // Missing key found in code
  'transcription.demo_empty_state': string;
  // Missing key found in code
  'transcription.final_transcript': string;
  // Missing key found in code
  'transcription.medical_ai_active': string;
  // Missing key found in code
  'transcription.no_transcript_description': string;
  // Missing key found in code
  'transcription.recording': string;
  // Missing key found in code
  'transcription.reset_demo': string;
  // Missing key found in code
  'transcription.service_browser': string;
  // Missing key found in code
  'transcription.service_label': string;
  // Missing key found in code
  'transcription.service_whisper': string;
  // Missing key found in code
  'transcription.transcribing': string;
  // Missing key found in code
  'transcription.words_count': string;
  // Missing key found in code
  'transform_now': string;
  // Missing key found in code
  'transformation_initiated': string;
  // Missing key found in code
  'transformation_plans': string;
  // Missing key found in code
  'transformation_voices': string;
  // Missing key found in code
  'transforming': string;
  // Missing key found in code
  'treatment_adherence_improved': string;
  // Missing key found in code
  'treatment_outcomes': string;
  // Missing key found in code
  'trust_promise': string;
  // Missing key found in code
  'trust_promise_desc': string;
  // Missing key found in code
  'update_treatment_plans': string;
  // Missing key found in code
  'welcome_to': string;
  
  // Dynamic key support
  [key: string]: string;
}

export type TranslationKey = keyof ENTranslations;

export interface TranslationParams {
  [key: string]: string | number;
}

export interface TranslationFunction {
  (key: TranslationKey, params?: TranslationParams): string;
}
