/**
 * Auto-generated TypeScript definitions for Spanish translations
 * Generated by Performance Revolution System
 */

export interface ESTranslations {
  // Core translations
  'transcription.title': string;
  'transcription.ready_to_record': string;
  'transcription.start_recording': string;
  'transcription.stop_recording': string;
  'transcription.no_transcript_available': string;
  
  // Language switcher translations
  'language_switcher.current_language': string;
  'language_switcher.medical_certified': string;
  'language_switcher.medical': string;
  'language_switcher.medical_grade': string;
  'language_switcher.validated': string;
  'language_switcher.change_language': string;
  'language_switcher.select_language': string;
  
  // Common translations
  'spanish': string;
  'english': string;
  'spanish_abbr': string;
  'english_abbr': string;
  'clinical_language': string;
  
  // Navigation
  'navigation.dashboard': string;
  
  // Common actions
  'save': string;
  'cancel': string;
  'edit': string;
  'delete': string;
  'create': string;
  'update': string;
  'actions': string;
  
  // Theme
  'light_mode': string;
  'dark_mode': string;
  
  // Demo
  'demo': string;
  'demo_mode_active': string;
  'switch_live_mode': string;
  'demo_login': string;
  'auto_fill_demo': string;
  'demo_mode_full_access': string;
  
  // Auth
  'email': string;
  'password': string;
  'login': string;
  'register': string;
  'login_demo': string;
  
  // Medical
  'consultation.page.title': string;
  'consultation.page.subtitle': string;
  'clinical.notes.title': string;
  'clinical.notes.subtitle': string;
  'orders.categories.medications': string;
  'orders.categories.lab_tests': string;
  'orders.categories.imaging': string;
  'orders.categories.consultations': string;
  
  // Recording
  'recording_started': string;
  
  // Workflow
  'workflow.steps.listen': string;
  'workflow.steps.review': string;
  'workflow.steps.notes': string;
  'workflow.steps.orders': string;
  'workflow.steps.summary': string;
  'workflow.title': string;
  'workflow.subtitle': string;
  'workflow.actions.stop_recording': string;
  'workflow.actions.start_recording': string;
  'workflow.consultation_flow': string;
  'workflow.step_of': string;
  'workflow.medical_navigation': string;
  'workflow.navigation.view_all_patients': string;
  'workflow.navigation.medical_reports': string;
  'workflow.navigation.clinical_history': string;
  'workflow.navigation.new_consultation': string;
  'workflow.current_step': string;
  'workflow.step_descriptions.listen': string;
  'workflow.step_descriptions.review': string;
  'workflow.step_descriptions.notes': string;
  'workflow.step_descriptions.orders': string;
  'workflow.step_descriptions.summary': string;
  
  // Demo specific
  'demo.demo_title': string;
  'demo.patient_selector': string;
  'demo.patient_selector_subtitle': string;
  'demo.request_custom_demo': string;
  
  // Dynamic key support
  [key: string]: string;
}

export type TranslationKey = keyof ESTranslations;

export interface TranslationParams {
  [key: string]: string | number;
}

export interface TranslationFunction {
  (key: TranslationKey, params?: TranslationParams): string;
}