import './globals.css'
import { EdgeStoreProvider } from './lib/edgestore'


export const metadata = {
  title: 'SYMFARMIA',
  description: 'Generated by Ar2Design',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans" style={{backgroundColor: '#F9FAFB'}}>
        <EdgeStoreProvider>
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  )
}
